hertz:
#  host: 192.168.18.6
#  port: 30000
  host:
  port: 8080

jwt:
  signingKey: CloudWeRun
  identityKey: id

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: huangzhitao123
  dbName: douyin
  maxOpenConn: 100
  maxIdleConn: 10

videoCRCRedis:
  host: localhost
  port: 6379
  password:
  db: 0
  poolSize: 100

videoFRCRedis:
  host: localhost
  port: 6379
  password:
  db: 1
  poolSize: 100

userInfoRCRedis:
  host: localhost
  port: 6379
  password:
  db: 2
  poolSize: 100